#what is the goal of your workflow
#goal: whwnever someone changes the python code.
#the linter will check the syntax , format , identation(Linitng) is correct or not
name: Auto Linter

on:
  push:
    paths: "*.py"

jobs:
  code:
    runs-on: ubuntu-latest
    #this step will automatically clone the code of the current branch into the runner
    steps:
      - name: Checkout/clone the code
        uses: actions/checkout@v7
        # this step will install python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
     # this will install the linitng tool
      - name: Install Linter
        run: pip install ruff
     # this will run the linter
      - name: Check the files for linting
        run: ruff check .
